---
name: work_item_tasks_on_boards
description: Show work item tasks on issue boards
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/469544
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/209068
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/577427
milestone: '18.6'
group: group::project management
type: wip
default_enabled: false
