---
name: secrets_manager_update_project_secret
description: This event is triggered when a project level secret is updated by a user
introduced_by_issue: https://gitlab.com/gitlab-org/gitlab/-/issues/554056
introduced_by_mr: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/205780
feature_category: secrets_management
milestone: '18.6'
saved_to_database: true
streamed: true
scope: [Project]

