---
name: secrets_manager_read_project_secret
description: This event is triggered when a CI pipeline job reads the value of a project
  level secret from Openbao
introduced_by_issue: https://gitlab.com/gitlab-org/gitlab/-/issues/554056
introduced_by_mr: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/205780
feature_category: secrets_management
milestone: '18.6'
saved_to_database: false
streamed: true
scope: [Project]

