---
api_type: string
attr: gitpod_url
clusterwide: false
column: gitpod_url
db_type: text
default: "'https://app.ona.com/'::text"
description: The Ona instance URL for integration.
encrypted: false
gitlab_com_different_than_default: false
jihu: false
not_null: false
