---
name: ci_delete_objects_high_concurrency
description: Feature flag to up the concurrency of delete objects worker
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/572897
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/207144
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/573391
milestone: '18.5'
group: group::pipeline execution
type: gitlab_com_derisk
default_enabled: false
