---
name: ci_improved_destroy_old_pipelines_worker
description: When enforcing retention policies we want to delete pipelines directly without canceling them or trigger callbacks
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/515449
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/204039
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/571100
milestone: '18.5'
group: group::ci platform
type: gitlab_com_derisk
default_enabled: false
