---
name: ci_require_api_token_for_ci_lint
description: Require API authentication for GET CI Lint endpoint
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/209764
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/209764
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/578076
milestone: '18.6'
group: group::pipeline authoring
type: gitlab_com_derisk
default_enabled: false
