---
name: enable_invalid_scope_error
description: Enable raising of InvalidScopeError from rate limit checks
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/573720
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/207325
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/573882
milestone: '18.5'
group: group::ci platform
type: gitlab_com_derisk
default_enabled: false
