---
name: enforce_runners_request_limit
description: Enforce app limits to runner requests instead of only logging
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/462537
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/206712
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/571740
milestone: '18.5'
group: group::ci platform
type: gitlab_com_derisk
default_enabled: false
