---
name: environment_attributes_from_job_environment
description: Fetch environment information from Environments::Job model instead of Ci::BuildMetadata
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/552372
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/202162
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/567649
milestone: '18.5'
group: group::environments
type: gitlab_com_derisk
default_enabled: false
