---
name: fix_graphql_offset_pagination_preloads
description:
feature_issue_url:
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/209359
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/577854
milestone: '18.6'
group: group::pipeline execution
type: gitlab_com_derisk
default_enabled: false
