---
name: packages_refactor_group_packages_finder
description: Refactor group packages finder
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/548761
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/204326
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/568923
milestone: '18.5'
group: group::package registry
type: gitlab_com_derisk
default_enabled: false
