---
table_name: clusters_integration_prometheus
classes:
- Clusters::Integrations::Prometheus
feature_categories:
- incident_management
description: "(Deprecated) Persists information about prometheus cluster integration"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/59091
milestone: '13.11'
gitlab_schema: gitlab_main_org
sharding_key_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/409734
table_size: small
removed_in_milestone: '18.6'
removed_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/200513
