---
name: archive_authentication_events
description: Enables a daily cronjob that deletes `authentication_events` records that are out of retention period.
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/545007
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/207500
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/573714
milestone: '18.5'
group: group::authentication
type: ops
default_enabled: false
